#!/usr/bin/env bash
# This script list objects in an S3 bucket using the AWS CLI.

BUCKET_NAME="$1"

# Check if bucket name is provided
if [ -z "$1" ]; then
  echo "Error: No bucket name provided."
  exit 1
fi

echo "S3 objects in bucket: $BUCKET_NAME"
aws s3api list-objects --bucket "$BUCKET_NAME" 
