#!/usr/bin/env bash
# This script list S3 bucket using the AWS CLI.

echo "Listing all S3 buckets..."

aws s3 ls
aws s3api list-buckets

if [ $? -ne 0 ]; then
    echo "Error: Unable to list S3 buckets. Check your AWS credentials."
    exit 1
fi
