#!/usr/bin/env bash

echo "== Deploy S3 bucket via CFN"

STACK_NAME="cfn-s3-bucket-stack"

echo "Deleting CloudFormation stack: $STACK_NAME" 
aws cloudformation delete-stack \ 
    --stack-name "$STACK_NAME" \ 
    --region "us-east-1"