#!/usr/bin/env bash

echo "== Deploy S3 bucket via CFN"

STACK_NAME="cfn-s3-bucket-stack"

aws cloudformation deploy \
    --template-file template.yaml \
    --no-execute-changeset \
    --stack-name $STACK_NAME \
    --region us-east-1 \
    --capabilities CAPABILITY_NAMED_IAM